- frontend/src/components/Header.vue
Changed the language tags in the hamburger window to use the terms "English/Francais" rather than "EN/FR".
> CKAN-UI #387 - Change language tags to use "English" and "Francais"

- frontend/src/components/Header.vue
Rather than using "Language: English/Francais", simply use "English" or "Francais".
> CKAN-UI #387 - Remove "Language" portion of language string

- frontend/src/components/dataset/ResourceCard.vue
- frontend/src/components/pages/about.vue
- frontend/src/components/pages/dataset_view.vue
Per issue #448, I've added confirmation dialogs to the remove resource/dataset buttons. This is to reduce the risk of accidental deletions. I also snuck in a typo fix for "Succesfully udpated".
To keep things simple and not introduce too much new code, I'm using the browser's built-in confirmation boxes for now.
> Added confirmation dialogs for delete actions

- frontend/src/components/form/components/Upload.vue
Whenever an attempt is made to overwrite uploaded resources with new files, errors are often triggered behind the scenes. These errors are caused by URL validators being incorrectly applied to file upload objects. The errors are triggered anytime an existing resource has a resource upload type of URL and a new file upload is attempted. The effect is that the upload cannot proceed.
Although there was preexisting logic to vary the validators based on whether a URL or File Upload method is chosen, these only ran when the resource edit page first loaded, which is the time the file upload component first mounted. I have modified the code such that the list of applicable validators changes whenever the upload method changes.
> Fix for failed uploads in issue #457

- frontend/src/components/Header.vue
Per bcgov#425, I've updated the logout success message so that it is green and says "You're now logged out".
It looks like this now:
> Changed colour and content of logout success message

- frontend/src/components/Header.vue
Per bcgov#516 and its parent issue, bcgov#377, I've removed Dataset Usage from the hamburger menu.
> Removed dataset usage from hamburger menu

- frontend/src/components/dataset/ResourceCard.vue
- frontend/src/components/pages/dataset_view.vue
- frontend/src/components/pages/resource.vue
Per https://github.com/bcgov/ckan-ui/issues/448#issuecomment-892220711, updated deletion confirmation messages for datasets and resources to use unique wording which clearly indicates what will be deleted. Also added the resource delete confirmation dialog in a place it was missed, that being on the  resource pages themselves.
**Dataset deletion confirmation**
**Resource deletion confirmation**
> Changed deletion confirmation messages for resources and datasets

- frontend/src/components/pages/organization_view.vue
This is a cleanup patch to close out bcgov#495. The schema has been updated per PR https://github.com/bcgov/ckanext-bcgov-schema/pull/40, so we can now remove an obsolete code path from the UI. Now, only `description` fields are consulted for organizations and groups, not `notes`. Since the bug in bcgov#495 was already resolved by patching the schema repo, this PR is some final housekeeping which should not affect functionality.
> Removed logic to pull from notes field

- frontend/src/components/pages/organizations.vue
bcgov#498 refers - the list of organizations at https://beta-catalogue.data.gov.bc.ca/organization is not filtered according to the provided keywords. The feature appears to have been designed to return the parent organizations that either included the provided keywords or contained sub-organizations which included the keywords. That is not how it was implemented however. Instead, the first N parent organizations in the global list were returned, where N is the number of matching parent organizations. There is a trivial fix to restore the intended behaviour, implemented here.
There is room for improvement to make the search less naive (it tries to match exact substrings for the entire search term) and also to make it more functional, for example by filtering the suborganizations as well …
> Fix broken organization filtering

- frontend/src/components/dataset/ResourceCard.vue
Per bcgov#494, hiding file sizes from resource cards if they're 0.0 MB. Simple logical change to account for the fact that file sizes are expressed as numeric strings like '0'.
> bcgov#494 - hide filesize if 0

- frontend/src/components/form/DynamicForm.vue
- frontend/src/components/pages/resource.vue
Per bcgov#489, I removed a couple of UI elements from the OFI resource screens. These elements include the download button, which is not applicable to geographic warehouse resources, and the URL field. These are hidden in the same conditions as are used to determine whether the OFI/POW "Request Access" button is shown.
To accomplish this, I added a generic field exclusion capability to the DynamicForm component and excluding the URL field according to the value of the loadPOW conditional.
> bcgov#489 - hiding download button and url for ofi resources

- frontend/src/components/dataset/ResourceCard.vue
- frontend/src/components/pages/resource.vue
- frontend/src/components/pow/powButton.vue
- frontend/src/i18n/en.js
- frontend/src/i18n/fr.js
For bcgov#364, changed the wording for the "Download" and "Request Access" buttons to use the verbiage "Access/Download" universally. This button uses the "open in new" icon which conforms with precedent set by classic catalogue.
> Updated button wording for accessing or downloading resources

- frontend/src/components/Header.vue
- frontend/src/i18n/en.js
- frontend/src/i18n/fr.js
Added a link to the hamburger menu per bcgov#535. Also removed some commented out menu links; will rely on git commit history to restore them if ever needed. French translation for documentation is documentation according to Google translate.
> Added Documentation to the hamburger menu

- backend/routes/auth.js
Users do not currently have to enter credentials when they click log in immediately after logging out. This remedies that, per bcgov#542.
> Fix logout behaviour

- frontend/src/components/DeleteButton.vue
- frontend/src/components/dataset/ResourceCard.vue
- frontend/src/components/pages/dataset_view.vue
- frontend/src/components/pages/resource.vue
Per bcgov#518, replaced the browser-native confirmation dialog for deletions with a custom one built on Vuetify.
- Baked this into a new component, `<DeleteButton>`, which allows delete handlers to be attached and messaging to be modified through properties
-  Did not change any of the logic for where and how this delete button is actually shown
The new dialog should look like this:
The button look and feel should remain the same.
> Added custom UI for delete modal

- Caddyfile
- frontend/vue.config.js
To keep classic CKAN API and the API bridge cleanly separated, sending all bridge API requests to a newly created apibridge/* route.
> Added apibridge/* route for API bridge traffic

- Caddyfile
- backend/app.js
- backend/config/default.json
- backend/routes/auth.js
- backend/routes/ckan/misc.js
- backend/routes/seo.js
- frontend/src/components/Header.vue
- frontend/src/components/pages/home.vue
- frontend/src/components/user/user.vue
- frontend/src/services/analytics.js
- frontend/src/services/auth.js
- frontend/src/services/ckanApi.js
- frontend/src/services/powApi.js
- frontend/src/services/resourceApi.js
- frontend/src/services/solrApi.js
- frontend/src/services/version.js
- frontend/vue.config.js
In order to distinguish between client API routes and CKAN API routes, and in order to allow both to coexist comfortably using a single host name, all client API endpoints were moved over to `/client-api/*`.
> Updated client API to be accessible at different routes

- frontend/src/components/pages/group.vue
- frontend/src/components/pages/organization_view.vue
Per bcgov#566, removed the Follow buttons from the interface in order to work around a bug with the activity feed.
> Removed follow buttons

- frontend/src/components/dataset/ResourceCard.vue
- frontend/src/components/pages/resource.vue
- frontend/src/components/pow/powButton.vue
For bcgov#501, this sets the secureUrl parameter for the persistent order widget according to whether the dataset is downloadable by the public.
This solves a problem where secure custom downloads could not be initiated even if the requester has access privileges.
> Update secureUrl GET parameter for POW

- backend/config/default.json
- backend/routes/ckan/misc.js
- frontend/src/components/pages/about.vue
- frontend/src/services/ckanApi.js
Per bcgov#553, removed the dependency on a CKAN API key. The about page is now loaded client side from a configurable URL, currently set to https://raw.githubusercontent.com/bcgov/ckan-ui/pages/pages/about.md.
This required a corresponding helm chart update.
> Change to how about page is loaded

- backend/routes/ckan/datasets.js
Searches that contain mixed case tokens, like a search for HealthLinkBC, split at the boundaries of case transition, leading, e.g. to the aforementioned being treated as 3 tokens, "Health", "Link", and "BC". This can cause search relevance issues. That's because keyword matches in titles significantly boost relevance scores, so in the above example, titles that include the word "Link" get favoured over resources that contain the word "HealthLinkBC".
This works around the issue by lowercasing mixed case tokens before sending them to solr.
> Lowercase mixed case tokens to improve search relevance

- frontend/src/components/dataset/ListPage.vue
Currently, searches are modified to include an asterisk at the beginning and end of the query. This breaks things like phrase-based search and requires workarounds to benefit from the features of solr's query parser.
I've returned the code to the default behaviour, which does not introduce characters to user-provided search queries. This seems to improve search relevance and makes other search features easier to access.
> Stop wrapping search queries in asterisks

- backend/app.js
- backend/config/default.json
- backend/package-lock.json
- backend/package.json
- pages/changelog.md
I've added an option to save session information to a redis instance at a user-configurable host and port. This should improve the stability of session state, even in lieu of a HA configuration for Redis, because users won't get logged out every time the backend bridge's container crashes; a Redis pod is likely to be more stable.
New configuration values include:
- `redisHost`
- `redisPort`
- `redisPassword`
Both default to null.
> Added option to store sessions in Redis

- backend/package.json
I increased the heap size limit for node to 3.75GB to give it a little more room to breath.
> Increased memory limit for backend bridge

- backend/routes/ckan/organizations.js
With bcgov/ckanext-bcgov#890, /api/3/action/organization_list_related provides enough information without setting `all_fields` to True, and omitting that parameter makes the API call faster.
> Removed all_fields=True from organization_list_related API call

- backend/routes/ckan/user.js
- frontend/src/components/common/activityList.vue
- frontend/src/components/pages/user.vue
- frontend/src/services/ckanApi.js
- frontend/src/store/modules/user.js
Updated the user profile page to identify the current user via the newly minted whoami API call. The allows users without activity history to view their profile and retrieve their API key, as it no longer uses a heuristic that depends on activity history items.
> Use whoami

- frontend/src/components/dataset/ListCard.vue
Update ternary statement to fix `NaN - NaN - NaN` displaying when no publish date exists
> Update date ternary to check if date exists

- frontend/src/services/apiConfig.js
Not just an issue with loading /groups page but also loading individual groups.
> Up timeout to 15seconds

- frontend/src/components/groups/GroupCard.vue
- frontend/src/components/pages/groups.vue
Update groups page api calls to execute sequentially and not all at once to avoid api bottleneck and calls timing out.
- moved api call from GroupCard to groups page
- loop through group api calls, waiting on each promise to resolve before calling the next
> Update groups page api calls

- backend/package.json
- frontend/src/components/groups/GroupCard.vue
- frontend/src/components/pages/groups.vue
- frontend/src/services/apiConfig.js
- pages/changelog.md
For the groups page:
- move the api call from the GroupCard into the groups page
- wait for each api call to finish before running the next, preventing server overload/call timeouts
- add spinner to indicate loading
For the group pages:
- increase the api call timeout time (this is a temporary fix/bandaid while we look into why these calls take so long/rewrite them on the api side for improved efficiency)
> Fix group(s) page loading

- pages/changelog.md
Update changelog to include:
- replacement of gravitar with initials
- update of newest search to use record_publish_date instead of metadata_created
- fix of resource lifecycle history to prevent it overwriting other, similar, dates
> Update changelog for 2.1.5

- backend/package.json
- pages/changelog.md
Changes:
- Removed French toggle while fixing French setting | ([#785](https://github.com/bcgov/ckan-ui/pull/785))
- Added state to title component and removed state field | ([#784](https://github.com/bcgov/ckan-ui/pull/784))
- Add sitemap to redis cache | ([#782](https://github.com/bcgov/ckan-ui/pull/782))
- Remove final 'Not Provided' handling | ([#780](https://github.com/bcgov/ckan-ui/pull/780))
- Fixed composite field | ([#779](https://github.com/bcgov/ckan-ui/pull/779))
Updated version to 2.1.8
> Update changelog for release 2.1.8
