bcgov/ckan-ui

frontend/src/components/breadcrumb/Breadcrumb.vue
frontend/src/components/organizations/OrgTree.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/organizations.vue
frontend/src/i18n/en.js
frontend/src/i18n/fr.js
frontend/src/main.js

Ckan ui#59

---

frontend/src/components/breadcrumb/Breadcrumb.vue
frontend/src/components/groups/GroupCard.vue
frontend/src/components/organizations/OrgTree.vue
frontend/src/components/pages/groups.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/organizations.vue
frontend/src/i18n/en.js
frontend/src/i18n/fr.js
frontend/src/main.js

Ckan ui#60

---

frontend/src/components/Header.vue
frontend/src/components/pages/about.vue
frontend/src/components/pages/group.vue

Ckan ui#78

---

frontend/src/components/form/components/Tags.vue

Changed keywords field to a combobox, added comma delimiter to the field to support copy paste, and made input clear when an option is selected.

PR: Ticket #148

---

frontend/src/components/dataset/ListCard.vue
frontend/src/i18n/en.js
frontend/src/i18n/fr.js

Merge fix for issue #129

---

frontend/src/components/form/components/CompositeRepeating.vue

Fixed default population on composite repeating.

PR: Fixed #193

---

frontend/src/components/form/DynamicForm.vue
frontend/src/store/modules/dataset.js

Removed log message for facet creation

PR: Issue #186 - Removed log message for facet creation

---

backend/routes/ckan/datasets.js
frontend/src/components/form/components/Autocomplete.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/group.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/resource.vue

Made group and org have the same bar as resources/datasets and made the autocomplete more user friendly.

PR: Issue #196

---

Caddyfile
backend/app.js
backend/package-lock.json
backend/package.json
backend/routes/seo.js

see also [bcgov/ckanext-bcgov#170](https://github.com/bcgov/ckanext-bcgov/tree/ckan-ui%23170)

Ckan ui#170

---

.github/workflows/lint.yml
backend/app.js
backend/package-lock.json
backend/package.json
backend/routes/ckan/misc.js
backend/routes/ckan/organizations.js
backend/routes/resource.js
frontend/package.json

Adding a github action for running the linter on PRs.

Github action for running linter

---

frontend/src/components/dataset/ResourceCard.vue

See also https://github.com/bcgov/ckanext-bcgov-schema/pull/14

changed resource card to use resource description

---

frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/group.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/resource.vue

I was unable to reproduce the issue after some of the changes I made to schema so let's try this

changed alert bar to make it more visible on edit pages

---

.gitignore
backend/README.md
backend/package-lock.json
backend/package.json
backend/routes/seo.js

Refactor robots.txt to update based on ENV for DEV/TEST/PROD deploy.

Refactor robots.txt

---

frontend/src/components/form/DynamicForm.vue
frontend/src/components/form/components/StateMachine.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/router/index.js

This won't show up until this is also merged https://github.com/bcgov/ckanext-bcgov-schema/pull/24

Ckan UI#308

---

frontend/src/components/form/components/ImageUrl.vue
frontend/src/components/form/components/TextInput.vue
frontend/src/components/form/components/Upload.vue
frontend/src/components/organizations/edit.vue
frontend/src/components/pages/organization_view.vue

See also https://github.com/bcgov/ckanext-bcgov-schema/pull/32

tweaks to organization fields and url validation

---

frontend/src/components/pow/powButton.vue

Per bcgov#501, I've updated the UI to open OFI/POW in a new window instead of trying to embed it in a modal iframe. Siteminder has a security policy in place to prevent it from being embedded in iframes.

Open the OFI/POW dialog in a new window

---

frontend/public/index.html
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/resource.vue
frontend/src/main.js
frontend/src/router/index.js
frontend/src/store/modules/dataset.js

Dynamically generating page titles, per bcgov#551. Patterns outlined in ticket, but updated dataset and resource view to match title pattern used in prod classic catalogue.

Updated page titles for SEO

---

pages/changelog.md

Updated and removed misleading or unchanged values

Changelog updates - 09/14/2021

---

Caddyfile
frontend/vue.config.js

Reverts bcgov/ckan-ui#561 - need to update hardcoded values

Revert "Added apibridge/* route for API bridge traffic"

---

Caddyfile
backend/app.js
backend/config/default.json
backend/package-lock.json
backend/package.json
backend/routes/auth.js
backend/routes/ckan/misc.js
backend/routes/seo.js
frontend/package-lock.json
frontend/public/index.html
frontend/src/components/DeleteButton.vue
frontend/src/components/Header.vue
frontend/src/components/dataset/ResourceCard.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/home.vue
frontend/src/components/pages/resource.vue
frontend/src/components/user/user.vue
frontend/src/i18n/en.js
frontend/src/i18n/fr.js
frontend/src/main.js
frontend/src/router/index.js
frontend/src/services/analytics.js
frontend/src/services/auth.js
frontend/src/services/ckanApi.js
frontend/src/services/powApi.js
frontend/src/services/resourceApi.js
frontend/src/services/solrApi.js
frontend/src/services/version.js
frontend/src/store/modules/dataset.js
frontend/vue.config.js

In addition to some route updates (client-api vs api), migration includes:
- #542
- #518
- #551
- #501
- #535

Migrate from dev to test

---

Caddyfile
backend/app.js
backend/config/default.json
backend/routes/auth.js
backend/routes/ckan/misc.js
backend/routes/seo.js
frontend/package-lock.json
frontend/src/components/Header.vue
frontend/src/components/dataset/ResourceCard.vue
frontend/src/components/form/components/CompositeRepeating.vue
frontend/src/components/form/components/StateMachine.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/group.vue
frontend/src/components/pages/home.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/resource.vue
frontend/src/components/pow/powButton.vue
frontend/src/components/user/user.vue
frontend/src/mixins/permissions.vue
frontend/src/services/analytics.js
frontend/src/services/auth.js
frontend/src/services/ckanApi.js
frontend/src/services/powApi.js
frontend/src/services/resourceApi.js
frontend/src/services/solrApi.js
frontend/src/services/version.js
frontend/src/store/modules/organization.js
frontend/vue.config.js

Allows setting of state when admin of a parent org, and editing of a dataset now requires admin of that org or a parent org instead of the past admin of anything declaration

changes to support cascading auth in datasets

---

backend/routes/ckan/datasets.js
frontend/src/components/dataset/ListPage.vue
pages/changelog.md

This includes improvements to search query parsing; see changelog for more details.

Migrate dev to test

---

backend/package.json

Revert "Increased memory limit for backend bridge"

---

pages/changelog.md

Change links from /pages/pages to /master/pages.

Update documentation links

---

backend/package.json

Revert "Re-attempt max_old_space increase"

---

backend/package.json
frontend/public/index.html
frontend/src/components/dataset/ListPage.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/datasets.vue
frontend/src/components/pages/group.vue
frontend/src/components/pages/groups.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/organizations.vue
frontend/src/components/pages/resource.vue
frontend/src/components/pages/user.vue
frontend/src/router/index.js
pages/changelog.md

- update current version
- import snowplow frontend script
- add linkclick tracker update to most components
- add track page view after each route navigation
- update changelog to include snowplow events

Migrate snowplow config from Dev to Test

---

frontend/src/components/groups/GroupCard.vue

Readded watch, which was required to update GroupCard info
Added loading prop to watch so v-if / v-else would update
to

Readded required watch on GroupCard, added loading update to watch

---

frontend/src/components/groups/GroupCard.vue
frontend/src/components/pages/groups.vue

- remove dataset count from GroupCard
- remove callback loop from groups page

Remove dataset counts from groups

---

frontend/src/components/groups/GroupCard.vue
frontend/src/components/pages/groups.vue

- remove dataset count from GroupsCard
- remove callback loop from groups page

Remove dataset from groups

---

pages/about.md
pages/changelog.md

Merge changelog update to release.

Merge dev into release

---

backend/package.json
pages/changelog.md

Update changelog to include:
- fix to deletion of contacts and lifecycle dates
- removal of survey banner
Update package version number

Release 2.1.6 changelog

---

pages/changelog.md

Add release date

---

.gitignore
frontend/vue.config.js

Reversed last commit and unset API route changes

Dds 927 make dates clearable

---

backend/package.json
pages/changelog.md

Update version to 2.1.7
Update changelog to include changes from:
- 738
- 739
- 741
- 742
- 743
- 744
- 745

Update version, update changelog

---

frontend/src/main.js

Do not add gtag if not present

---

frontend/src/main.js

Revert "Do not add gtag if not present"

---

frontend/src/components/Footer.vue
frontend/src/components/Header.vue
frontend/src/components/dataset/FacetFilter.vue
frontend/src/components/dataset/FacetFilters.vue
frontend/src/components/organizations/OrgTree.vue
frontend/src/components/pages/home.vue

- add events for:
- formats tile
- facets
- open and close all
- open and close individuals
- adding and removing filters
- clearing filters
- header
- about page
- org list page
- refactor names, categories, and labels

Add events

---

frontend/src/components/form/DynamicForm.vue
frontend/src/components/form/components/CompositeRepeating.vue
frontend/src/components/form/components/StateMachine.vue
frontend/src/components/pages/dataset_view.vue

Updated composite repeating to pre-populate org fields if there is an orgId passed in.
Updated state machine to use orgId and lookup orgName

Changed orgName parameter on dynamic form to orgId which is more useful.

---

frontend/src/components/Header.vue
frontend/src/components/dataset/ListPage.vue
frontend/src/components/pages/home.vue
frontend/src/components/pages/organizations.vue

Reverts bcgov/ckan-ui#769
Potential PIA conflict so removing until resolved.

Revert "Add event to search bars"

---

backend/package.json
backend/routes/seo.js
frontend/src/components/Header.vue
frontend/src/components/form/DynamicForm.vue
frontend/src/components/form/components/Composite.vue
frontend/src/components/form/components/CompositeRepeating.vue
frontend/src/components/form/components/Json.vue
frontend/src/components/form/components/StateMachine.vue
frontend/src/components/form/components/Title.vue
pages/changelog.md

Removed French toggle while fixing French setting | (https://github.com/bcgov/ckan-ui/pull/785)
Added state to title component and removed state field | (https://github.com/bcgov/ckan-ui/pull/784)
Add sitemap to redis cache | (https://github.com/bcgov/ckan-ui/pull/782)
Remove final 'Not Provided' handling | (https://github.com/bcgov/ckan-ui/pull/780)
Fixed composite field | (https://github.com/bcgov/ckan-ui/pull/779)

Release 2.1.8

---

pages/changelog.md

Remove known issues that have been resolved

Release 2.1.8 update

---

backend/routes/seo.js

Increase sitemap timeout to 80 seconds

Release 2.1.8 - update

---

backend/package.json
frontend/src/components/form/components/Autocomplete.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/datasets.vue
frontend/src/components/pages/group.vue
frontend/src/components/pages/groups.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/organizations.vue
frontend/src/components/pages/resource.vue
pages/changelog.md

Changes:
- Fix background to cover smaller pages
- Updated autocomplete template to remove dense setting to match other formatting

Release 2.1.9

---

frontend/src/components/Header.vue
frontend/src/components/dataset/ListPage.vue
frontend/src/components/form/DynamicForm.vue
frontend/src/components/organizations/edit.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/group.vue
frontend/src/components/pages/groups.vue
frontend/src/components/pages/organization_view.vue
frontend/src/components/pages/resource.vue
frontend/src/mixins/permissions.vue
frontend/src/store/index.js
frontend/src/store/modules/organization.js
frontend/src/store/modules/user.js

- update authorization to pull from ckan instead of keycloak token
- load authorization in header

Update release 2.1.9

---

frontend/src/components/form/components/TextInput.vue
frontend/src/mixins/permissions.vue

- add safety checks for detecting dates
- additional fixes to permissions

Release 2.1.9 patch

---

pages/changelog.md

- Add validation check for dates
- Set docker node image version
- Refactor permission handling

Release 2.1.9 update changelog

---

frontend/src/components/Footer.vue
frontend/src/components/Header.vue
frontend/src/components/dataset/FacetFilter.vue
frontend/src/components/dataset/FacetFilters.vue
frontend/src/components/organizations/OrgTree.vue
frontend/src/components/pages/dataset_view.vue
frontend/src/components/pages/home.vue
frontend/src/components/pages/resource.vue

Refactored existing events with the idea to:
- reduce the number of custom events, adding more info/value to individual events
- stop tracking model/dropdown/etc closing (no added value)

Google analytics - refactor

---

backend/package.json
pages/changelog.md

- update release number
- update changelog with:
- Auth refactor | ([#828](https://github.com/bcgov/ckan-ui/pull/828))
- Admin panel for groups | ([#827](https://github.com/bcgov/ckan-ui/pull/827))
- Initial admin panel for orgs | ([#825](https://github.com/bcgov/ckan-ui/pull/825))
- Refactor GA events | ([#824](https://github.com/bcgov/ckan-ui/pull/824))
- Add events for Google analytics | ([#761](https://github.com/bcgov/ckan-ui/pull/761))
- Switch to vue-gtag for Google analytics | ([#752](https://github.com/bcgov/ckan-ui/pull/752))

Update changelog for release 2.2.0

---

frontend/src/components/pages/resource.vue
pages/changelog.md

- update release date
- add system date display

Update release 2.2.0

---

frontend/src/components/banner/Banner.vue

Revert "Error style banner activated with message regarding outage"

---

pages/changelog.md

- added original changes to changelog
- added recent changes to changelog

Update changelog for 2.2.1

---

frontend/src/components/banner/Banner.vue

This reverts commit 1c1a930c8f4aa8ebdfdce0d64c4703933a5b8c4c.

Reversed commit for outage banner

---

frontend/src/components/banner/Banner.vue

This reverts commit 93871644e84e6ae542c9c65c9f313dfd8c062c06.

Revert "Updated banner due to performance issues on July 12"

---

frontend/src/components/banner/Banner.vue

Revert "Temporary banner to be merged when outage starts"

---

frontend/src/components/banner/Banner.vue

Revert "Notification banner for planned outage"

---

.github/workflows/lint.yml

Change to an earlier version of ubuntu to fix node instal issue

Update ubuntu image

---

Dockerfile
Dockerfile-frontend

Update node version in frontend and backend dockerfiles

Update node version in Dockerfiles
